name: Daily Reminder

on:
  schedule:
    - cron: "48 17 * * *"
  workflow_dispatch:

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install python-telegram-bot==20.7 pytz

    - name: Run reminder script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
        THREAD_ID: ${{ secrets.THREAD_ID }}
      run: python cron_reminder.py
